use_frameworks!

target 'YFCodeScan_Example' do
  pod 'YFCodeScan', :path => '../'

  target 'YFCodeScan_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
